version: "3.9"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    environment:
      DATABASE_URL: postgres://admin:admin123@database:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  postgres_data:
